# Generated by Django 5.1.3 on 2024-11-19 19:12

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Category = apps.get_model('courses', 'Category')
    for category in Category.objects.all():
        base_slug = slugify(category.name)
        slug = base_slug
        counter = 1
        while Category.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        category.slug = slug
        category.save()

def reverse_populate_slugs(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
