# Generated by Django 5.1.3 on 2024-11-13 19:03

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_enrollment_options_enrollment_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='file',
            field=models.FileField(upload_to='course_contents/', validators=[courses.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The order in which this content appears in the course'),
        ),
    ]
