# Generated by Django 5.1.3 on 2024-11-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_populate_category_slugs'),
        ('courses', '0009_remove_enrollment_completed_and_more'),
    ]

    operations = [
    ]
